### ISSUE TITLE
End-of-central-directory signature not found

### ISSUE THREAD

**Issue by AljoSt** [remaro-network/SubPipe-dataset#3]
Hello thank you for sharing the dataset!

I get an error when trying to unzip the SubPipe.zip dataset (the small version works).

Archive:  SubPipe.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.

I checked the md5 hash of the file and it matches the one on the website. Given that it's not possible to preview the file on the website either, there might be something wrong with that file?

**Comment by antallaszlo011** [comment]
Hi there, thanks for reaching out!

I'm just wondering which version of SubPipe you're trying to unzip. On Zenodo, there are two versions available, and I believe you should be able to unzip version v2 without any errors.

Unfortunately, since the zip file was quite large (and at that moment, I had barely enough space on my computer), I think the first zip file has corruption. We will address this issue soon (most likely by just removing v1 from Zenodo).

Let me know if this helps. :)

**Comment by AljoSt** [comment]
Ah didn't see v2. Thanks, this seems to work :+1:
